# Generated by Django 3.0.8 on 2020-08-31 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('query', models.CharField(max_length=200)),
            ],
        ),
    ]
